[book]
authors = ["Sirius"]
language = "zh"
multilingual = false
src = "src"
title = "Sirius运维开发笔记"
description = "Sirius运维开发笔记"

[rust]
edition = "2021"

[build]
build-dir = "SiriusBlog"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = false
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/einsli/SiriusBlog"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/einsli/SiriusBlog/edit/main/{path}"
input-404 = "not-found.md"
additional-js = ["language.js"]

[output.html.print]
enable = true

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = false
copy-js = true
line-numbers = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true